# time it

In [2]:
%timeit [j**4 for j in range(1,9)]

409 ns ± 43.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [1]:
import numpy as np
%timeit np.arange(1,9)**4

2.28 μs ± 248 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [2]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
# y = np.array([1,2,3,4])
# print(y)
print(type(y))
print(y.ndim)

<class 'numpy.ndarray'>
1


In [7]:
l = []
for i in range(1,5):
    int_1 = int(input("Enter the number : "))
    l.append(int_1)
print(np.array(l))

Enter the number :  29
Enter the number :  31
Enter the number :  25
Enter the number :  26


[29 31 25 26]


In [4]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [6]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [8]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
