# Zeros

In [3]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [6]:
ar_1 = np.ones(4)
print(ar_1)

[1. 1. 1. 1.]


# empty

In [7]:
ar_em = np.empty(5)
print(ar_em)

[2.12199579e-314 4.67296746e-307 7.11454530e-321 9.10344484e-312
 3.23953608e-008]


# Range

In [8]:
ar_rn = np.arange(5)
print(ar_rn)

[0 1 2 3 4]


# Diagonal

In [9]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [12]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
