# Random

In [11]:
import numpy as np

var = np.random.rand(4)
print(var)


[0.84641429 0.34711259 0.07089797 0.99322322]


In [6]:
var1 = np.random.rand(3,4)
print(var1)

[[0.10742306 0.72058632 0.07010217 0.58203751]
 [0.03852184 0.0589922  0.53898038 0.10271302]
 [0.69950841 0.92636071 0.30958096 0.06455858]]


In [9]:
var2 = np.random.randn(4)
print(var2)

[ 0.83450392 -0.79944131 -1.33082349 -0.4890605 ]


In [10]:
var3 = np.random.ranf(4)
print(var3)

[0.05409531 0.55458084 0.73009707 0.83445569]


In [12]:
var4 = np.random.randint(1,20,5)
print(var4)

[15  3 19 19 16]
