In [2]:
import numpy as np
var = np.array([11,12,15,18])
varadd = var + 3
varsub = var - 1
varmul = var * 3
vardiv = var / 2
varmod = var % 2
varpow = var ** 3
varrec = 1 / var
print(varadd)
print(varsub)
print(varmul)
print(vardiv)
print(varmod)
print(varpow)
print(varrec)

[14 15 18 21]
[10 11 14 17]
[33 36 45 54]
[5.5 6.  7.5 9. ]
[1 0 1 0]
[1331 1728 3375 5832]
[0.09090909 0.08333333 0.06666667 0.05555556]


In [5]:
var1 = np.array([6,8,5,2],dtype = np.int64)
var2 = np.array([15,16,17,18],dtype = np.int64)
varadd2 = var1+ var2
varsub2 = var2 - var1
varmul2 = var2 * var1
vardiv2 = var2 / var1
varmod2 = var2 % var1
varpow2 = var2 ** var1
print(varadd2)
print(varsub2)
print(varmul2)
print(vardiv2)
print(varmod2)
print(varpow2)

[21 24 22 20]
[ 9  8 12 16]
[ 90 128  85  36]
[2.5 2.  3.4 9. ]
[3 0 2 0]
[  11390625 4294967296    1419857        324]


In [8]:
var1 = np.array([6,8,5,2],dtype = np.int64)
var2 = np.array([15,16,17,18],dtype = np.int64)
varadd2 = np.add(var2,5)
varsub2 = np.subtract(var2,5)
varmul2 = np.multiply(var2,var1)
vardiv2 = np.divide(var,var1)
varmod2 = np.mod(var2,var1)
varpow2 = np.power(var2,var1)
varrec = np.reciprocal(var2)
print(varadd2)
print(varsub2)
print(varmul2)
print(vardiv2)
print(varmod2)
print(varpow2)
print(varrec)

[20 21 22 23]
[10 11 12 13]
[ 90 128  85  36]
[1.83333333 1.5        3.         9.        ]
[3 0 2 0]
[  11390625 4294967296    1419857        324]
[0 0 0 0]


# 2d array

In [9]:
var22 = np.array([[1,2,3,4],[5,6,7,8]])
var21 = np.array([[1,2,3,4],[5,6,7,8]])

varadd22 = np.add(var22,var21)
print(varadd22)

[[ 2  4  6  8]
 [10 12 14 16]]
