In [5]:
import numpy as np
var = np.array([47,31,18,26])
print(f"min : {np.min(var)} {np.argmin(var)}")
print(f"max : {np.max(var)} {np.argmax(var)}")

min : 18 2
max : 47 0


In [10]:
var2 = np.array([[21,28,3],[9,98,43,]])
print(f"min : {np.min(var2)}")
print(f"min along row :  {np.min(var2, axis = 0)}")
print(f"min along column:  {np.min(var2, axis = 1)}")

min : 3
min along row :  [ 9 28  3]
min along column:  [3 9]


In [11]:
print(np.sqrt(var))

[6.8556546  5.56776436 4.24264069 5.09901951]


In [14]:
print(np.sin(var))
print(np.cos(var))

[ 0.12357312 -0.40403765 -0.75098725  0.76255845]
[-0.99233547  0.91474236  0.66031671  0.64691932]


In [15]:
print(np.cumsum(var))

[ 47  78  96 122]
