# Shape

In [3]:
import numpy as np
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var, "\n")
print(var.shape)

[[1 2 3 4]
 [5 6 7 8]] 

(2, 4)


In [4]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1.ndim)
print(var1.shape)

4
(1, 1, 1, 4)


# Reshape

In [8]:
x = np.array([1,2,3,4])
print(x)
print(x.ndim)
x2 = x.reshape(2,2)#no of elements must be same as in orignal array
print(x2)
print(x2.ndim)

[1 2 3 4]
1
[[1 2]
 [3 4]]
2


In [9]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
print(x.ndim)
x3 = x.reshape(2,3,2)#no of elements must be same as in orignal array
print(x3)
print(x3.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [13]:
one = x3.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
