# Broadcasting error

In [5]:
import numpy as np

var1 = np.array([1,2,3])
print(var1)
print()
print(var1.ndim)
print()

var2 = np.array([[1],[2],[3]])
print(var2)
print()
print(var2.ndim)
print()

ans = var1 + var2
print(ans)
print()
print(ans.ndim)


[1 2 3]

1

[[1]
 [2]
 [3]]

2

[[2 3 4]
 [3 4 5]
 [4 5 6]]

2


In [11]:
x = np.array([[1] ,[2]])
print(x.shape)
y = np.array([[1,2,3],[2,3,4]])
print(y.shape)
print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [4 5 6]]
