# Copy vs View

In [5]:
import numpy as np
var = np.array([1,2,3]) 

y = var.copy()
var[1] = 4
print(y)
print(var)

[1 2 3]
[1 4 3]


In [6]:
var = np.array([1,2,3])

y = var.view()
var[1] = 4
print(y)
print(var)

[1 4 3]
[1 4 3]
