# Concatenate

In [3]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

z = np. concatenate((x, y))
print(z)

[1 2 3 4 9 8 7 6]


In [22]:
var = np.array([[1,2],[3,4]])
var1 = np.array([[9,8],[7,6]])

ar = np. concatenate((var, var1),axis = 0)
print(ar)
print()
ar = np. concatenate((var, var1),axis = 1)
print(ar)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


# stack

In [27]:
var2 = np.array([[1,2],[3,4]])
var3 = np.array([[9,8],[7,6]])

ar1 = np.stack((var2, var3),axis = 0)
print(ar1)
print()

ar2 = np.hstack((var2, var3)) # row
print(ar2)
print()

ar3 = np.vstack((var2, var3)) # column
print(ar3)
print()

ar4 = np.dstack((var2, var3)) # height
print(ar4)
print()

[[[1 2]
  [3 4]]

 [[9 8]
  [7 6]]]

[[1 2 9 8]
 [3 4 7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[[1 9]
  [2 8]]

 [[3 7]
  [4 6]]]

