# Search

In [4]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,2,4,5,6,7,4,])
x = np.where((var%2)==0)
print(x)

(array([ 1,  3,  5,  7,  9, 10, 12, 14], dtype=int64),)


In [6]:
var1 = np.array([1,2,3,4,6,7,8,9])
x1 = np.searchsorted(var1,5)
print(x1)

4


In [12]:
var2 = np.array([1,2,3,4,8,9])
x2 = np.searchsorted(var2,5,side="Right")
x3 = np.searchsorted(var2,[5,6,7],side="Right")

print(x2)
print(x3)

4
[4 4 4]


# Sort

In [13]:
var2 = np.array([1,2,3,4,5,6,7,8,9,2,4,5,6,7,4,])
print(np.sort(var2))

[1 2 2 3 4 4 4 5 5 6 6 7 7 8 9]


In [14]:
var3 = np.array(["S","P","D","M","S","P"])
print(np.sort(var3))

['D' 'M' 'P' 'P' 'S' 'S']


In [15]:
var4 = np.array([[1,21,3],[44,53,6]])
print(np.sort(var4))

[[ 1  3 21]
 [ 6 44 53]]


# Filter

In [19]:
var5 = np.array(["S","P","D","M","S","P"])
f = [False,True,False,True,False,False]
arr = var5[f]
print(arr)

['P' 'M']
