# more array Functions

In [8]:
import numpy as np

var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var) # if I give y = np.random.shuffle(var) it will give None as output

[2 4 3 5 1]


In [10]:
var1 = np.array([1,2,2,3,4,5,4,4,1,3])
x = np.unique(var1)
y = np.unique(var1,return_index = True,return_counts=True)
print(x) # if I don't provide x here than there will be no change in orignal matrix
print(y)

[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([0, 1, 3, 4, 5], dtype=int64), array([2, 2, 2, 3, 1], dtype=int64))


In [11]:
var2 = ([1,2,3,4,5,6,7,8,9])
x = np.resize(var2,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


In [18]:
var3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var3.flatten())#by default C- row
print(var3.flatten(order= "F")) # column

print(var3.ravel())
print(var3.ravel(order= "F"))
print(var3.ravel(order= "K"))

[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
