# insert

In [6]:
import numpy as np

var = np.array([1,2,3,4])
x= np.insert(var, 2, 40)
y = np.insert(var,(2,4),(10,20))
z = np.insert(var,(3,4),50)
print(x)
print(y)
print(z)
print(var)

[ 1  2 40  3  4]
[ 1  2 10  3  4 20]
[ 1  2  3 50  4 50]
[1 2 3 4]


In [14]:
var1 = np.array([[1,2,3,],[4,5,6]])
x1= np.insert(var1, 1, 40, axis = 0)
y1 = np.insert(var1,1,20,axis = 1)
z1= np.insert(var1,1,[3,4,5],axis = 0)
print(x1)
print(y1)
print(z1)

[[ 1  2  3]
 [40 40 40]
 [ 4  5  6]]
[[ 1 20  2  3]
 [ 4 20  5  6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [16]:
var2 = np.array([[1,2,3,],[4,5,6]])
x2 = np.append(var2, [[6.5,44, 23]],axis= 0)
print(x2)

[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 6.5 44.  23. ]]


# Delete

In [17]:
d = np.delete(var2,(0,2))
print(d)

[2 4 5 6]
