# Matrix

In [8]:
import numpy as np
var = np.matrix([[1,2],[1,2]])
var1= np.matrix([[5,6],[3,4]])
print(var.dot(var1))

[[11 14]
 [11 14]]


In [12]:
var2= np.matrix([[5,6],[3,4],[3,2]])
x = np.transpose(var2)
print(x)
print(var2.T)

[[5 3 3]
 [6 4 2]]
[[5 3 3]
 [6 4 2]]


In [16]:
var3= np.matrix([[5,6],[3,4]])
print(np.swapaxes(var3,1,0))

[[5 3]
 [6 4]]


In [19]:
var4= np.matrix([[1,2],[3,4]])
print(np.linalg.inv(var4))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))
print()

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [28]:
var5= np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(np.linalg.det(var5))

0.0
