In [45]:
import numpy as np
import random
import time

In [48]:
list1 = [29,32,48,29,26,29]
list2 = [69,23,12,13,37,24]
start = time.time()
list3 = []
for i , j in zip(list1, list2):
    list3.append(i*j)
print(list3)
end = time.time()
print(end - start)

[2001, 736, 576, 377, 962, 696]
0.0004317760467529297


In [49]:
arr1 = np.array([29,32,48,29,26,29])
arr2 = np.array([69,23,12,13,37,24])
start = time.time()
arr3 = arr1*arr2
print(arr3)
end = time.time()
print(end-start)

[2001  736  576  377  962  696]
0.0004134178161621094


In [83]:
l = []
for i in range(1,10):
    var = np.random.randint(1,10)
    l.append(var)
    x = np.array(l, ndmin = 1)
    i +=1
print(x)
x= x.reshape(3,3)
print(x)
print(x.shape)
y = x.flatten()
print(y)

[8 8 3 1 3 5 4 1 3]
[[8 8 3]
 [1 3 5]
 [4 1 3]]
(3, 3)
[8 8 3 1 3 5 4 1 3]


In [75]:
x2 = np.array([1.1 , 2.2 , 3.3])
print(x2.dtype)
x2 = x2.astype(int)
print(x2.dtype)

float64
int64


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
mask = arr >5
print(arr[mask])

[ 6  7  8  9 10]


In [88]:
condition = (arr%2 == 0)
fancy = np.extract(condition , arr)
print(fancy)

[ 2  4  6  8 10]
